import { mkdir, readFile, writeFile } from "node:fs/promises";

const assets = [
  ["/", "public/index.html", "text/html; charset=UTF-8", "no-cache", false],
  ["/index.html", "public/index.html", "text/html; charset=UTF-8", "no-cache", false],
  ["/styles.css", "public/styles.css", "text/css; charset=UTF-8", "public, max-age=3600", false],
  ["/script.js", "public/script.js", "text/javascript; charset=UTF-8", "public, max-age=3600", false],
  ["/faithcraft-logo.jpg", "public/faithcraft-logo.jpg", "image/jpeg", "public, max-age=604800, immutable", true],
  ["/robots.txt", "public/robots.txt", "text/plain; charset=UTF-8", "public, max-age=3600", false],
  ["/sitemap.xml", "public/sitemap.xml", "application/xml; charset=UTF-8", "public, max-age=3600", false],
];

const loaded = await Promise.all(
  assets.map(async ([path, file, contentType, cacheControl, binary]) => {
    const body = await readFile(file);
    return [
      path,
      {
        body: binary ? body.toString("base64") : body.toString("utf8"),
        contentType,
        cacheControl,
        encoding: binary ? "base64" : "utf8",
      },
    ];
  }),
);

const worker = `// Generated by scripts/build.mjs. Edit files in public/ instead.\n` +
`const assets = new Map(${JSON.stringify(loaded)});\n` +
`const securityHeaders = {\n` +
`  "Content-Security-Policy": "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; script-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self' mailto:",\n` +
`  "Referrer-Policy": "strict-origin-when-cross-origin",\n` +
`  "Permissions-Policy": "camera=(), microphone=(), geolocation=()",\n` +
`  "X-Content-Type-Options": "nosniff",\n` +
`  "X-Frame-Options": "DENY",\n` +
`  "Cross-Origin-Opener-Policy": "same-origin",\n` +
`};\n` +
`export default {\n` +
`  async fetch(request) {\n` +
`    const url = new URL(request.url);\n` +
`    if (request.method !== "GET" && request.method !== "HEAD") {\n` +
`      return new Response("Method Not Allowed", { status: 405, headers: { Allow: "GET, HEAD" } });\n` +
`    }\n` +
`    const asset = assets.get(url.pathname);\n` +
`    if (!asset) {\n` +
`      return new Response("Not Found", { status: 404, headers: securityHeaders });\n` +
`    }\n` +
`    const headers = new Headers(securityHeaders);\n` +
`    headers.set("Content-Type", asset.contentType);\n` +
`    headers.set("Cache-Control", asset.cacheControl);\n` +
`    const body = asset.encoding === "base64" ? Uint8Array.from(atob(asset.body), (char) => char.charCodeAt(0)) : asset.body;\n` +
`    return new Response(request.method === "HEAD" ? null : body, { status: 200, headers });\n` +
`  },\n` +
`};\n`;

await mkdir("src", { recursive: true });
await writeFile("src/worker.js", worker);
console.log(`Built src/worker.js with ${loaded.length} routes.`);

